[package]
name = "litterbox"
version = "0.1.0"
edition = "2024"
default-run = "litterbox"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
